// Shared styles for all auth components
export const authStyles = {
  wrapper: {
    minHeight: "100vh",
    width: "100vw",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0fff0",
    position: "relative",
    overflow: "hidden",
    margin: 0,
    padding: 0,
  },
  backgroundLogo: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    opacity: 0.20,
    pointerEvents: "none",
    zIndex: 1,
    objectFit: "cover",
  },
  container: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.5rem",
    padding: "2.5rem",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: "16px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.1)",
    width: "400px",
    maxWidth: "90vw",
    backdropFilter: "blur(10px)",
  },
  title: {
    fontSize: "2rem",
    color: "#2c3e50",
    marginBottom: "0.5rem",
    textAlign: "center",
    fontWeight: "bold",
  },
  roleBadge: {
    backgroundColor: "#4caf50",
    color: "white",
    padding: "0.5rem 1rem",
    borderRadius: "20px",
    fontSize: "1rem",
    fontWeight: "500",
    marginBottom: "1rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    width: "100%",
  },
  input: {
    padding: "1rem",
    fontSize: "1rem",
    borderRadius: "8px",
    border: "1px solid #ddd",
    outline: "none",
    width: "100%",
    transition: "border-color 0.3s, box-shadow 0.3s",
    backgroundColor: "white",
  },
  inputFocus: {
    borderColor: "#4caf50",
    boxShadow: "0 0 0 2px rgba(76, 175, 80, 0.2)",
  },
  button: {
    padding: "1rem",
    fontSize: "1.1rem",
    fontWeight: "bold",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    width: "100%",
    marginTop: "0.5rem",
  },
  backButton: {
    padding: "0.8rem",
    fontSize: "1rem",
    fontWeight: "bold",
    backgroundColor: "#95a5a6",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    width: "100%",
    marginTop: "0.5rem",
  },
  message: {
    marginTop: "0.5rem",
    fontSize: "0.9rem",
    textAlign: "center",
    maxWidth: "300px",
    wordBreak: "break-word",
    padding: "0.5rem",
    borderRadius: "4px",
  },
  successMessage: {
    backgroundColor: "#d4edda",
    color: "#155724",
    border: "1px solid #c3e6cb",
  },
  errorMessage: {
    backgroundColor: "#f8d7da",
    color: "#721c24",
    border: "1px solid #f5c6cb",
  },
  helpText: {
    marginTop: "1rem",
    fontSize: "0.9rem",
    color: "#666",
    textAlign: "center",
  },
  debugInfo: {
    marginTop: "0.5rem",
    fontSize: "0.8rem",
    color: "#666",
    textAlign: "left",
    maxWidth: "300px",
    wordBreak: "break-word",
    backgroundColor: "#f5f5f5",
    padding: "0.5rem",
    borderRadius: "4px",
    border: "1px solid #ddd",
  }
};